"""email module: mailboxes and parse failures

Revision ID: 13f27fc685a3
Revises: 9dda8ed2109b
Create Date: 2026-07-29 19:55:49.842491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f27fc685a3'
down_revision: Union[str, None] = '9dda8ed2109b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailboxes',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=False),
    sa.Column('provider', sa.Enum('MAILHOG', 'IMAP', 'GRAPH', name='mailbox_provider'), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', name='mailbox_status'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('parse_failures',
    sa.Column('mailbox_id', sa.Uuid(), nullable=False),
    sa.Column('raw_subject', sa.String(length=500), nullable=True),
    sa.Column('raw_from', sa.String(length=320), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=False),
    sa.Column('raw_source', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parse_failures')
    op.drop_table('mailboxes')
    # ### end Alembic commands ###
