"""knowledge module: articles versions chunks nodes gaps

Revision ID: 9dda8ed2109b
Revises: ff9678fcb995
Create Date: 2026-07-29 19:27:31.839845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '9dda8ed2109b'
down_revision: Union[str, None] = 'ff9678fcb995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_gaps',
    sa.Column('cluster_key', sa.String(length=120), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'DRAFTING', 'CLOSED', name='knowledge_gap_status'), nullable=False),
    sa.Column('sample_request_refs', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_articles',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_versions',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'APPROVED', 'INDEXED', 'ARCHIVED', name='knowledge_version_status'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('access_level', sa.Enum('PUBLIC', 'INTERNAL', 'RESTRICTED', name='access_level'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['knowledge_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_nodes',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('locator', sa.String(length=40), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'evidence', 'knowledge_chunks', ['chunk_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_table('knowledge_chunks')
    op.drop_table('knowledge_nodes')
    op.drop_table('knowledge_versions')
    op.drop_table('knowledge_articles')
    op.drop_table('knowledge_gaps')
    # ### end Alembic commands ###
