"""add threshold and stages to decisions

Revision ID: ff9678fcb995
Revises: 44ee7bc224b8
Create Date: 2026-07-29 19:03:58.199102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9678fcb995'
down_revision: Union[str, None] = '44ee7bc224b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('threshold', sa.Numeric(precision=5, scale=4), nullable=False, server_default='0.95'))
    op.add_column('decisions', sa.Column('stages', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'stages')
    op.drop_column('decisions', 'threshold')
    # ### end Alembic commands ###
